name: GHA Task
on:
  workflow_dispatch:
jobs:
  GHA_Task:
    runs-on: ubuntu-latest
    steps:
        #Run Discovery
      - name: Run Discovery
        id: discovery
        uses: NeuraLegion/run-discovery@v1.1
        with:
          api_token: ${{ secrets.ISAH_GHA_TASK }}
          name: GHA Task - Isah Disc
          project_id: ${{ vars.PROJECT_ID }}
          discovery_types: |
            [ "crawler" ]
          crawler_urls: |
            [ "https://brokencrystals.com/" ]
            
      - name: Wait for discovery to finish
        id: wait
        uses: NeuraLegion/wait-for-discovery@v1
        with:
          api_token: ${{ secrets.ISAH_GHA_TASK }}
          discovery_id: ${{ steps.discovery.outputs.id }}
          project_id: ${{ vars.PROJECT_ID }}
          timeout: 8899
          
      - name: List Project Entrypoints
        id: entrypoints
        uses: NeuraLegion/list-entrypoints@v1.1
        with:
          api_token: ${{ secrets.ISAH_GHA_TASK }}
          project_id: ${{ vars.PROJECT_ID }}
          limit: 15
          connectivity: ok
          status: new,vulnerable
          ids_only: true
        
      - name: Start Bright Scan
        id: scan
        uses: NeuraLegion/run-scan@release
        with:
          api_token: ${{ secrets.ISAH_GHA_TASK }}
          project_id: ${{ vars.PROJECT_ID }}
          entrypoints: ${{ steps.entrypoints.outputs.entrypoints }}
          name: GHA Scan Isah
       
      - name: Get the output scan url
        run: echo "The scan was started on ${{ steps.scan.outputs.url }}"

      - name: Wait for Medium
        id: medium
        uses: NeuraLegion/wait-for@release
        with:
          api_token:  ${{ secrets.ISAH_GHA_TASK }}
          scan: ${{ steps.scan.outputs.id }}
          wait_for: medium
          timeout: 7123
          stop_scan: true
