name: GHA Task
jobs:
 GHA_TASK
 #Run Discovery
  - name: Start Bright Discovery Isah Task
    id: start
    uses: NeuraLegion/run-discovery@v1.1
    with:
      api_token: ${{ secrets.Isah_GhA_Task }}
      name: GHA - Isah Task
      project_id: pqbeJVvVSjKbgivMZgxS57
      discovery_types: |
        [ "crawler" ]
      crawler_urls: |
        [ "http://brokencrystal.com" ]
        auth_object_id: 7rFF7PmgBEKXPkoewzcoKp
